import { StyleNarrative } from "@/lib/disc/types";

export const styleNarratives: Record<"D" | "I" | "S" | "C", StyleNarrative> = {
  D: {
    style: "D",
    title: "Dominance",
    overview: "You lead with pace, ownership, and outcomes. You are often the person who creates direction when ambiguity is high.",
    coreMotivators: ["Autonomy", "Challenge", "Measurable wins"],
    strengths: ["Decisive in uncertainty", "Sets bold direction", "Drives accountability"],
    blindSpots: ["Can move faster than team readiness", "May under-communicate context", "Can appear impatient"],
    communicationStyle: "Direct, concise, and action-oriented. Prefers decisions over lengthy discussion.",
    underStress: "May become overly controlling, blunt, or dismissive of slower voices.",
    leadershipTips: ["Share the 'why' before the 'what'", "Pause to invite dissenting input", "Set check-in points instead of micromanaging"],
    delegationTips: ["Delegate outcomes and constraints", "Align on decision rights upfront"],
    meetingStyle: "Short, focused, and milestone-driven.",
    conflictStyle: "Addresses conflict quickly and head-on.",
    decisionStyle: "High speed, high ownership, willing to decide with incomplete data.",
    teamExperience: "Your team sees you as clear and bold, and may sometimes wish for more context.",
    growthEdge: "Balance urgency with inclusion so execution quality stays high.",
    oppositeStylePartnership: "Partner with S leaders to improve sustainability and team adoption of fast decisions.",
    bestFitResponsibilities: ["Turnaround efforts", "Strategic pivots", "Crisis leadership"]
  },
  I: {
    style: "I",
    title: "Influence",
    overview: "You lead through connection, optimism, and momentum. You often energize people and create buy-in around change.",
    coreMotivators: ["Recognition", "Collaboration", "Creative momentum"],
    strengths: ["Builds engagement", "Persuasive communicator", "Creates positive team climate"],
    blindSpots: ["Can overcommit", "May avoid hard trade-offs", "Execution details can slip"],
    communicationStyle: "Warm, expressive, and audience-aware. Strong at shaping narrative.",
    underStress: "May become scattered, overly optimistic, or avoid difficult conversations.",
    leadershipTips: ["Translate vision into concrete milestones", "Use written follow-up for decisions", "Set boundaries on commitments"],
    delegationTips: ["Pair inspiration with explicit ownership", "Assign detail-oriented partners for follow-through"],
    meetingStyle: "Interactive, idea-rich, and collaborative.",
    conflictStyle: "Prefers preserving relationships, may delay direct confrontation.",
    decisionStyle: "People-informed and opportunity-focused.",
    teamExperience: "Your team experiences you as motivating and approachable, with room for sharper prioritization.",
    growthEdge: "Add structure to your influence so momentum consistently becomes outcomes.",
    oppositeStylePartnership: "Partner with C leaders to pressure-test ideas and improve execution reliability.",
    bestFitResponsibilities: ["Culture initiatives", "Stakeholder alignment", "Change communication"]
  },
  S: {
    style: "S",
    title: "Steadiness",
    overview: "You lead with consistency, trust, and team stability. You build durable execution environments where people can do their best work.",
    coreMotivators: ["Stability", "Team trust", "Predictable progress"],
    strengths: ["Reliable follow-through", "Strong listener", "Builds loyal teams"],
    blindSpots: ["Can resist rapid change", "May avoid tension", "Can hold back dissenting views"],
    communicationStyle: "Calm, empathetic, and respectful. Prefers context and clarity over urgency.",
    underStress: "May withdraw, delay decisions, or default to harmony at the expense of speed.",
    leadershipTips: ["Speak up early when risks surface", "Practice concise decision framing", "Use experiments to build comfort with change"],
    delegationTips: ["Set clear checkpoints", "Challenge team members with stretch responsibilities"],
    meetingStyle: "Inclusive, structured, and supportive.",
    conflictStyle: "Seeks mediation and practical compromise.",
    decisionStyle: "Consensus-aware and methodical.",
    teamExperience: "Your team sees you as dependable and fair, and may look to you for stronger urgency in fast moments.",
    growthEdge: "Increase decisiveness during transition periods while preserving your relational strengths.",
    oppositeStylePartnership: "Partner with D leaders to increase speed while maintaining team trust.",
    bestFitResponsibilities: ["People leadership", "Operational continuity", "Cross-functional coordination"]
  },
  C: {
    style: "C",
    title: "Conscientiousness",
    overview: "You lead with rigor, quality, and precision. You raise standards and reduce risk through thoughtful planning.",
    coreMotivators: ["Quality", "Accuracy", "Competence"],
    strengths: ["Strong analytical judgment", "High standards", "Reliable planning"],
    blindSpots: ["Can overanalyze", "May appear critical", "Can delay action for more certainty"],
    communicationStyle: "Structured, factual, and clear. Prefers evidence over assumptions.",
    underStress: "May become overly cautious, perfectionistic, or rigid in process.",
    leadershipTips: ["Define 'good enough' thresholds", "Communicate priorities, not only risks", "Invite faster-cycle decisions where stakes are lower"],
    delegationTips: ["Delegate decision boundaries, not just tasks", "Coach others on quality criteria"],
    meetingStyle: "Agenda-driven, detail-focused, and decision documented.",
    conflictStyle: "Uses data and standards to resolve disagreements.",
    decisionStyle: "Evidence-based and risk-aware.",
    teamExperience: "Your team experiences you as thoughtful and reliable, and may need more speed signals from you.",
    growthEdge: "Pair your quality mindset with faster execution rhythms.",
    oppositeStylePartnership: "Partner with I leaders to broaden influence and accelerate stakeholder alignment.",
    bestFitResponsibilities: ["Governance and risk", "Operational design", "Performance optimization"]
  }
};
